server:
  port: 8085

spring:
  application:
    name: cdgenerator-spring-boot-starter
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: *
    username: *
    password: *

logging:
  config: classpath:logback-spring.xml
  path: logs/

cdgenerator:
  #文件生成默认作者
  author: sha
  #文件输出路径
  output-dir: D:/
  #父级包名
  parent-package: com
  #controller层包名
  controller-package: D:/controller
  #server层包名
  server-package: D:/service
  #mapper层包名
  mapper-package: D:/dao
  #entity层包名
  entity-package: D:model
  #是否略过视图
  skip-view: true
  copyright: Fih
  #表名称配置，多个用逗号隔开，若全部则为All。注意不同数据库大小写敏感
  tables: TB_Course
